### ISSUE TITLE
EnergyMixer on Energiepodiumdiner.nl doesn't seem to work anymore

### ISSUE THREAD

**Issue by dennisquintel** [quintel/energymixer#238]

**Comment by dennisquintel** [comment]
Error:

```
Error: {"errors":["Input transport_useful_demand_ships does not exist"]}
```

**Comment by dennisquintel** [comment]
including @jorisberkhout @ChaelKruip and @AlexanderWirtz

**Comment by RobTerwel** [comment]
```
Error: {"errors":["Input transport_useful_demand_ships does not exist"]}
```

That input statement is now called `transport_useful_demand_ship_kms`.

**Comment by dennisquintel** [comment]
> That input statement is now called transport_useful_demand_ship_kms.

:+1: Thanks!

**Comment by dennisquintel** [comment]
@RobTerwel could you try to adapt the input statements in the database?

**Comment by RobTerwel** [comment]
:+1: I'll try and ask @grdw for help if need be.

**Comment by dennisquintel** [comment]
> :+1: I'll try and ask @grdw for help if need be.

Thanks!

**Comment by RobTerwel** [comment]
The input statements have been updated to `transport_useful_demand_ship_kms`. However, there is an input which no longer exists: `gas_from_middle_east_share` was deleted in https://github.com/quintel/etsource/pull/1007, because it had been replaced (in kind) by `lng_from_qatar_share` <a href="https://github.com/quintel/etsource/commit/3558a611c1988b1462e0bfb7e2bd061437a7b965"a>here<a/>. 

I see two main options:
- replacing `gas_from_middle_east_share` with `lng_from_qatar_share` which results in the problem that the shares don't add up to 100% since they are part of different `share_groups`.
- removing `gas_from_middle_east_share` and adding the value previously assigned to it to `gas_from_algeria_share` 

@dennisschoenmakers @AlexanderWirtz @ChaelKruip @jorisberkhout , do you have a preference or alternative ideas?

**Comment by jorisberkhout** [comment]
I prefer the second option.

**Comment by dennisquintel** [comment]
> I prefer the second option.

I'm okay with that!

**Comment by RobTerwel** [comment]
> > I prefer the second option.
> 
> I'm okay with that!

Done! However, I stumbled on one more thing: the hybrid heatpump (HHP) input statement was misspelt, which I fixed. But as a consequence of replacing the HP _add on_ with the (HHP) in this <a href="https://github.com/quintel/energymixer/commit/e418ea24416aea221572c58c52f2220fd7da80e1"a> PR<a/>, we now have an overfull share group for `heating_households` for question 8 answer D:

"Oude en nieuwe gebouwen zijn goed geïsoleerd en maken gebruik van de nieuwste verwarmingstechnieken (HRe, warmtepompen op gas of elektriciteit, hout-CV kachels en gasgestookte brandstofcellen)."

gives

```
heating_households" group does not balance: group sums to 110.0 using 
households_space_heater_heatpump_ground_water_electricity_share=55.0 
households_space_heater_micro_chp_network_gas_share=15.0 
households_space_heater_coal_share=0.0 
households_space_heater_combined_network_gas_share=0.0
households_space_heater_electricity_share=0.0 
households_space_heater_hybrid_heatpump_air_water_electricity_share=10.0 
households_space_heater_network_gas_share=5.0 
households_space_heater_district_heating_steam_hot_water_share=10.0
households_space_heater_crude_oil_share=0.0 
households_space_heater_wood_pellets_share=15.0 
households_space_heater_heatpump_air_water_electricity_share=0.0
```

Can I subtract 10.0 from `households_space_heater_heatpump_ground_water_electricity_share` or does any of you have a different victim in mind?

**Comment by ChaelKruip** [comment]
> Can I subtract 10.0 from households_space_heater_heatpump_ground_water_electricity_share or does any of you have a different victim in mind?

:+1:

**Comment by RobTerwel** [comment]
Done!

Closing.
